EFFECTIVE_DISTANCE:
  2.0

cam_intrinsics_455: [ 
    416.933837890625, 0.0, 420.8775634765625,
    0.0, 416.361328125, 245.99343872070312,
    0.0, 0.0, 1.0
  ]

cam_ugv_extrinsics: [
  -0.00150876, -1.22465e-16, 0.999999, 0.0381075,
  1.84769e-19, -1.0, -1.22465e-16, -0.009544,
    0.999999,   0.0,   0.00150876, 0.0279997,
    0, 0,           0,           1
] 

# cam_ugv_extrinsics: [
#   0.0, 0.0, 1.0,    0.0,
#     0.0, -1.0, 0.0,   0.0004171,
#     1.0, 0.0, 0.0,   0.0009303,
#     0, 0,           0,           1, 0.0,   
# ] 

    

cam_ugv_euclidean_extrinsics_d455: [0.54446, 0.0, 0.0307356, -0.248458, -25.3396, 180.0] #xyzrpy


cam_FOV_H: 90
cam_FOV_V: 65

final_corridor_height: 0.60
final_corridor_length: 1.2

landing_horizontal: 1.6

LED_r_number: 3 #2
LED_g_number: 3


LED_temp: -0.04
LED_positions:
  - x: -0.10775
    y: -0.09875
    z: 0.031 #

  - x: 0.06025
    y: -0.0189001
    z: -0.02523

  - x: -0.08185
    y: 0.019
    z: 0.0

  - x: 0.10075
    y: 0.0505
    z: 0.02777

  - x: -0.10775
    y: 0.09875
    z: 0.031




ARUCO_positions:
  - x: 0.0
    y: 0.4
    z: -0.055
  - x: 0.0
    y: -0.0225
    z: -0.055
  - x: 0.0
    y: -0.0225
    z: -0.010
  - x: 0.0
    y: 0.0225
    z: -0.010

weightpath:
  "/home/patty/alan_ws/src/alan/offb/src/include/yolo/uav_new.weights"

cfgpath:
  "/home/patty/alan_ws/src/alan/offb/src/include/yolo/uav_new.cfg"

classnamepath:
  "/home/patty/alan_ws/src/alan/offb/src/include/yolo/uav.names"


MAD_dilate:
  10.0
MAD_max:
  0.1


BINARY_threshold:
 140

frame_width:
 848
frame_height:
 480

failsafe_threshold:
 0.20

failsafe_on:
 1 
 #1 on, 
 #0 off

# KF-related
Q_val:
 0.016
R_val_p:
 0.008
R_val_v:
 0.016
Q_alpha:
 0.3
R_beta:
 0.4
kf_size:
 9
kfZ_size:
 5
velo_IIR_alpha:
 0.98
OPT_MAX_ITERATION:
 25
CONVERGE_THRESHOLD:
 0.01
KF_ON:
 true


hover_thrust:
  0.5656