# whether the path/traj is predefined
predefined: true

# trajtype
TrajType: CIRCLE_TRAJ
# CIRCLE_TRAJ, BLOCK_TRAJ, LEMNISCATE_TRAJ, HOVER

# center
x0: 0.1
y0: 0.1
z0: 0.8

# misc
pub_freq: 100
lap_no: 400
ccw: true

# z move or not
z_moving: true
z_moving_amp: 0.14
z_moving_perioud: 7.5

# circle
circle_velo: 48.0 # dg/s
circle_radius: 0.24

# block
block_velo: 0.4 # m/s
block_length: 2
block_AR: 1
block_T_angle: 0.0

# lemniscate
amp: 1.4
lemi_velo: 60.0 # dg/s
timePerLap: 2.0


starting_error: 2.0

global_offset_x: 0.0
global_offset_y: 0.0
global_offset_z: 0.0